import { Client } from "discord.js";
import { registerReadyHandler } from "./ready";
import { registerMessageHandler } from "./messageCreate";
import { registerMemberUpdateHandler } from "./guildMemberUpdate";
import { registerServerLogEvents } from "./serverLogs";
import { registerAntiNukeEvents } from "./antinuke";
import { registerAntiRaidEvents } from "./antiraid";
import { registerTicketButtons } from "./ticketButtons";
import { registerApplicationButtons } from "./applicationButtons";
import { registerInviteTracking } from "./inviteTrack";
import { registerChannelCreate } from "./channelCreate";
import { registerMemberJoin } from "./guildMemberAdd";
import { registerMessageUpdate } from "./messageUpdate";
import { registerSnipeEvents } from "./snipeEvents";
import { registerGiveawayButtons } from "./giveawayButtons";
import { registerMemberLeave } from "./guildMemberRemove";
import { registerRolePanelInteractions } from "./rolePanelInteractions";
import { registerStarboardEvents } from "./starboardEvents";
import { registerSuggestionVotes } from "./suggestionVotes";
export function registerEvents(client: Client) {
  registerReadyHandler(client);
  registerMessageHandler(client);
  registerMessageUpdate(client);
  registerMemberUpdateHandler(client);
  registerServerLogEvents(client);
  registerAntiNukeEvents(client);
  registerAntiRaidEvents(client);
  registerTicketButtons(client);
  registerApplicationButtons(client);
  registerInviteTracking(client);
  registerChannelCreate(client);
  registerMemberJoin(client);
  registerMemberLeave(client);
  registerRolePanelInteractions(client);
  registerSnipeEvents(client);
  registerGiveawayButtons(client);
  registerStarboardEvents(client);
  registerSuggestionVotes(client);
}
